export GIT_AUTHOR_EMAIL="git@mcevoypeter.com"
export GIT_AUTHOR_NAME="Peter McEvoy"
export GIT_COMMITTER_EMAIL="git@mcevoypeter.com"
export GIT_COMMITTER_NAME="Peter McEvoy"
export PYENV_ROOT="$HOME/.pyenv"
